// Supabase Configuration
export const SUPABASE_URL = "https://hvmxltyneaarfxjgsrpb.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bXhsdHluZWFhcmZ4amdzcnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTYzMjAsImV4cCI6MjA3OTg5MjMyMH0.9-AOYnUuF8JR9XXVeHoCeluKFAjUDx_X4-vtO8y30sA";
